project:
  type: website
  output-dir: _site
  
#date: today
#date-format: "YYYY"

website:
  title: "Automated Management of AWS Instances"
  favicon: images/cloud-span-icon.png
  page-navigation: true         # prev and next options at the bottom of each page
  back-to-top-navigation: true
  reader-mode: true  
  repo-url: https://github.com/Cloud-SPAN/nerc-metagenomics-v2q
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2021–24 by [Cloud-SPAN](https://cloud-span.york.ac.uk/)    
#      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2021–{{<meta date>}} by [Cloud-SPAN](https://cloud-span.york.ac.uk/)\
#      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2018–{{<meta date>}} by the [Carpentries](https://carpentries.org/)\
#      Licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) 2016–2018 by the [Data Carpentry](https://datacarpentry.org/)      
    # center:
    #   - text: "About"
    #     href: about.qmd
    #   - text: "FAQ"
    #     href: docs/faq/index.qmd
    #   - text: "License"
    #     href: license.qmd
    #   - text: "Trademark"
    #     href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/SpanCloud
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/Cloud-SPAN/nerc-metagenomics-v2q
        aria-label: Quarto GitHub
      # - icon: rss
      #   href: https://quarto.org/docs/blog/index.xml
      #   aria-label: Quarto Blog RSS
  navbar:
    background: lightblue
    logo: images/cloud-span-icon.png
    logo-alt: "Cloud-SPAN logo."
    title: false
    collapse-below: lg
    left:
      - text: Home  
        href: index.qmd
      - text: Precourse Instructions
        href: docs/miscellanea/precourse-instructions.qmd
      - text: About
        href: docs/miscellanea/about.qmd
#       - text: License
#         href: docs/miscellanea/license.qmd
#       - text: Code of Conduct
#         href: docs/miscellanea/codeofconduct.qmd
#       - text: Help
#        menu:
#          - text: "Report a Bug"
#            icon: "bug"
#            href: "https://github.com/quarto-dev/quarto-cli/issues"
#          - text: "Ask a Question"
#            icon: "chat-right-text"
#            href: "https://github.com/quarto-dev/quarto-cli/discussions"
#          - text: "FAQ"
#            icon: "question-circle"
#            href: docs/faq/index.qmd
  
  sidebar:
    style: "docked"
    collapse-level: 1
    pinned: true
    contents:
      - section: "Setting Up Cloud/Terminal Environments"
        href: docs/lesson01-setting-work-envs/index.qmd
        contents: 
          - docs/lesson01-setting-work-envs/01-create-aws-account.qmd 
          - docs/lesson01-setting-work-envs/02-configure-account.qmd
          - docs/lesson01-setting-work-envs/03-configure-terminal.qmd
          - docs/lesson01-setting-work-envs/04-configure-cloudshell.qmd
      - section: "Managing AWS Instances"
        href: docs/lesson02-managing-aws-instances/index.qmd
        contents: 
          - docs/lesson02-managing-aws-instances/01-configure-instances-internet.qmd
          - docs/lesson02-managing-aws-instances/02-instances-management.qmd
          - docs/lesson02-managing-aws-instances/03-amis-management.qmd
          - docs/lesson02-managing-aws-instances/03-scripts-design.qmd

format:
  html:
    code-copy: true
    # highlight-style: oblivion, haddock or monochrome # dracula # espresso #(nice greyish)
    highlight-style: dracula
    code-overflow: wrap
    page-layout: full
    theme: cosmo
    css: styles.css
#    theme:
#    - styles.scss
    toc: true
    grid:                     # defaults
      sidebar-width: 230px    # 300px
      body-width: 1040px      # 900px
      margin-width: 230px     # 300px
      gutter-width: 1.5rem    # 1.5rem

execute:
  freeze: auto

editor: visual

